project:
  type: book
  output-dir: docs


book:
  title: "My Learning Diary QBook"
  author: "Tariro Mashongamhende"
  date: "2/11/2025"
  chapters:
    - index.qmd
    - ld_week_1.qmd
    - ld_week_2.qmd
    - ld_week_3.qmd
    - ld_week_4.qmd
    - ld_week_6.qmd
    - ld_week_7.qmd
    - ld_week_8.qmd
    - ld_week_9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt

editor: visual

